[package]
name = "fit-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fitparser="0.5.1"
anyhow="1.0.68"
rusqlite="0.28.0"
tui="0.19"
crossterm="0.25"
chrono="0.4.23"
itertools = "0.10.5"
